spring:
    application:
        name: order-service
    data:
        mongodb:
            uri: 'mongodb+srv://purely_db_user:purelywebapp@purely-webapplication-c.2y4ssug.mongodb.net/purely_productdb?retryWrites=true&w=majority&appName=purely-webapplication-cluster'
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9070

eureka:
  client:
    serviceUrl:
      defaultZone: http://100.25.212.194:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
   preferIpAddress: true
   instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}