spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: 'mongodb+srv://purely_db_user:purelywebapp@purely-webapplication-c.2y4ssug.mongodb.net/purely_productdb?retryWrites=true&w=majority&appName=purely-webapplication-cluster'
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost