spring:
    application:
        name: product-service
    data:
        mongodb:
            uri: ${SPRING_DATA_MONGODB_URI}
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9010

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost