kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-registry-deployment
  labels:
    app: service-registry-deployment
  namespace: purely-webapp-dev
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-registry 
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: 566855233164.dkr.ecr.us-east-1.amazonaws.com/service-registry:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8761